- bliss/core/bin/bliss_tlm_csv.py
Update handling of --all and --fields so that either one is required.
Before --fields was always required so specifying --all didn't work as
expected.
Add support for ground time queries. To use ground receipt time pass
the --ground_time flag when calling the script.
Resolve #23
> Issue #23 - Update Tlm to CSV script to support ground receipt time

- README.md
- setup.py
Resolves #17. Depends on #16 and #21.
- Add descriptions and url to setup.py
- Document PyPi process in gh wiki (https://github.com/NASA-AMMOS/AIT-Core/wiki/Uploading-Releases-to-PyPi)
Test package can be seen at: https://test.pypi.org/project/bliss-core/
If this looks good I can push the package to PyPi for real.
> Issue #17 - Prepare to publish AIT-Core to Pypi

- bliss/core/notify.py
- bliss/core/test/test_notify.py
- data/config/config.yaml
- doc/source/bliss.core.notify.rst
- doc/source/bliss.core.rst
- doc/source/bliss.core.test.rst
- doc/source/bliss.core.test.test_notify.rst
Add `bliss.core.notify` for sending email and text notifications. The
`notify` module has support for sending email and text (or both)
notifications via SMTP.
Add new bliss.config section for notifications. Notification supports
config for email and text notifications and for SMTP server connection
information.
A notification type has a list of "triggers" which specifies the name(s)
of triggers for which that type of event should be emitted. These are
used in conjunction with `bliss.config.notify.trigger_notification()`
so that components can submit triggers for notifications while allowing
the user to control what type (if any) of notification is emitted.
A notification type also has a list of "recipients". For both email and
text notifications these are email addresses.
SMTP server …
> Issue #31 - Add text and email notification support

- .travis.yml
- README.md
> Issue #36 - Add Travis CI Build

- .github/CODEOWNERS
This should result in the committers and PMC groups being automatically included as code owners on a pull request
Resolve #39
> Issue #39 - Add CODEOWNERS

- build/githooks/pre-commit
- setup.py
Git hook install now checks to make sure that the .git/hooks directory
exists before attempting to copy the hook script into location. This
ensures no error shows up when installing from a non-cloned version of
the code base.
Remove the git hook install from non-develop mode installs. If someone
is installing the toolkit in 'install' mode instead of 'develop' mode
the likelihood of them making changes that the hook would catch seems
slim.
Update the packaging naming in the git hook
Resolve #65
> Issue #65 - Fix git hooks install on non-checkout version of repo

- ait/core/bin/ait_tlm_db_insert.py
- ait/core/db.py
- ait/core/dtype.py
- ait/core/test/test_db.py
- doc/source/ait.core.test.rst
- doc/source/ait.core.test.test_db.rst
- doc/source/databases.rst
- doc/source/index.rst
Add the GenericBackend abstract base class in core.db for defining the
expected interface for interacting with databases through AIT. Add
the SQLiteBackend sub-class which implements the previous core.db
backend functionality. Add the InfluxDBBackend sub-class which adds
support for InfluxDB to the toolkit.
Deprecate all previous core.db functions. Users should instead use the
SQLiteBackend class if they require the previous functionality. All
previous core.db functions will be removed in a future release.
Add tests for the new core.db backend classes
Update ait-tlm-db-insert to use the new backend classes. It also expects
to receive data in PCAPs instead of generic binary blobs in a file since
PCAPs are the project baseline for data storage.
Resolve #81 
Resolve #85
> Issue #85 - Expand core.db backend support

- ait/core/notify.py
* Subject defaults to 'AIT Notification'.
* From defaults to 'ait-notify@my.smtp.server'
This update also includes a bug fix for s.sendmail(). First argument is
supposed to be from_addr [1]:
SMTP.sendmail(from_addr, to_addrs, msg[, mail_options, rcpt_options])
[1] https://docs.python.org/2/library/smtplib.html#smtplib.SMTP.sendmail.
Testing in past must have used SMTP server that did not check to verify
from_addr was an email format (e.g. ait@gmail.com).
Another note from testing is the from_addr MUST have a valid @server in
order to work for text messaging. At least while testing with AT&T, it appears
they perform a check to verify it is a legitimate domain prior to sending.
Interestingly enough, it does not bounce the message with an error, it
simply drops it to the floor.
Resolves #97
> Issue #97: add configurable subject and from address

- ait/core/bin/ait_pcap.py
Updated --stime and --etime flag help messages. Updated formats to
YY-MM-DDThh:mm:SSZ, and updated defaults and examples to match this
format. Updated etime default to "current time" rather than an example
time, and relabeled the provided time "example".
> Issue #79: ait-pcap help message cleanup

- doc/source/installation.rst
Updated typos in install documentation.
Added message to ignore config parameter path warnings when
checking installation.
Resolves #63
> Issue #63 - Typos in install documentation

- ait/core/dtype.py
- ait/core/evr.py
- ait/core/test/test_evr.py
EVR message format string processing has been updated to better handle
type and size format information. Data conversion has been switched over
to the dtype.PrimitiveType class so that processing of binary values
into ints/floats returns expected values.
Resolve #112
> Issue #112 - Expand EVR Format Message Handling

- .gitignore
- ait/core/bin/ait_cmd_send.py
Added `host` argument to `ait_cmd_send.py` script which defaults to `"127.0.0.1"`.
Resolves #25
> Issue #25 - bliss_cmd_send hardcoded to 127.0.0.1

- .gitignore
- ait/core/bin/ait_tlm_simulate.py
- ait/core/tlm.py
Added `simulate` method to `PacketDefinition` class and used it to send dummy packet data to host and port of choice in `ait_tlm_simulate.py`.
Resolves #75
> Issue #75 - Create script for generating dummy telemetry data for tests

- ait/core/test/__init__.py
Removing reload of default config file on test initialization.
Resolves #124
> Issue #124 - Config file reload on test initialization uses relative path

- ait/core/dtype.py
Current functionality did not properly handle unknown EVRs. This provides
more graceful handling to output warning messages versus raising
and exception.
resolves #129
> Issue #129: Update EVRType to better handle unknown EVRs

- ait/core/server/server.py
Plugin creation function now passes the configuration object to the
constructor as expected. Required attributes are removed from the
configuration dictionary prior to Plugin creation.
Resolve #141
> Issue #141 - Fix issue with optional Plugin attrs not being passed

- ait/core/server/client.py
Switch all message sent/receive log messages from info to debug. Minor
cleanup of ZMQInputClient sub.recv handling code to remove extra string
joins and temp variables.
Resolve #142
> Issue #142 - Reduce server.client log message noise

- ait/core/server/client.py
Update PortOutputClient so that raw message data is output without
additional stream name information. This ensures that output data
format is consistent with pre-server expectations.
Resolve #150
> Issue #150 - PortOutputClient to dump raw message data

- config/config.yaml
Update the server section of config.yaml so the log_stream port is set to 2514 (the expected log port in the rest of the toolkit)
Resolve #149
> Issue #149 - Update default log_stream port

- setup.py
influxDB requires requests>=2.17.0 while AIT-CORE required 2.9.1. Upgraded to the required version number. Change was tested out by sending sequences via AIT GUI.
> Issue #138 - Updated python requests version number

- ait/core/dtype.py
- ait/core/test/test_dtype.py
- config/cmd.yaml
Also added new example command to the cmd.yaml that has a single string argument.  Resolves #66
> Issue #66 - Strarg validation includes err mesg when arg is numeric

- doc/source/command_intro.rst
> Issue #69 - Update command config docs with byte ordering details

- ait/core/server/plugins/openmct.py
- doc/source/ait.core.server.plugins.openmct.rst
- doc/source/ait.core.server.plugins.rst
- doc/source/ait.core.server.rst
- doc/source/index.rst
- doc/source/plugin_openmct.rst
- openmct/README
- openmct/ait_cfg_section.yaml
- openmct/ait_integration.js
This PR introduces:
1) new standalone OpenMct plugin (residing under ait/core/server/plugins), which provides OpenMCT formatted results;
2) modified ait_integration.js  (originally in AIT-GUI repo), which interacts with the plugin;
3) Documentation for a user to perform the integration into OpenMct deployment.
Resolve #204
> Issue #204 - Create a standalone OpenMCT plugin

- ait/core/bin/ait_mps_seq_convert.py
- doc/source/ait.core.bin.ait_mps_seq_convert.rst
- doc/source/ait.core.bin.rst
Add ait_mps_seq_convert for converting MPS Sequence files to AIT
sequence files. Outputs an MPS sequences as an absolute time and
relative time sequence to provide flexibility for planning and
operations teams. Note that the absolute time sequence is provided even
though AIT will only run and encode the relative time sequence
currently.
Resolve #202
> Issue #202 - Add MPS Seq to AIT Seq conversion script

- ait/core/cmd.py
- ait/core/data/cmd_schema.json
- config/cmd.yaml
- config/core_set_op_mode.yaml
* Created additional command yaml file `core_set_op_mode.yaml` - command was copied from [AIT-Core Users Guide](https://ait-core.readthedocs.io/en/latest/command_intro.html)
* Updated `cmd_schema.json` and `cmd.py` to add `!include` capability
FYI, below is the `ait-yaml-validate --cmd`, `Cmd.encode()`, and `Cmd.decode()` outputs:
> Issue #167 - Add !include capability to cmd.yaml

- ait/core/cmd.py
- ait/core/test/test_val.py
- ait/core/test/testdata/val/testCmdValidator1.yaml
- ait/core/test/testdata/val/testCmdValidator2.yaml
- ait/core/val.py
Update CmdDict.add so duplicate opcodes or command names result in a
raised exception. This mirrors the TlmDict handling.
Update command dicitonary load during validation to create a CmdDict
object instead of loading the YAML "manually." This is necessary to
support included commands
Update command validation checks to handle raised exceptions for
duplicate opcode and command names. Fix error in duplicate opcode test
so commands don't have duplicate names as well.
Resolve #206
> Issue #206 - Fix command duplicate opcode / name validation

- config/config.yaml
Issue #216 - Update server.plugins default value in config to an empty
list so it doesn't fall back to None. This prevents it from breaking
other code that checks if the value exists and falls back to a sane
default if it doesn't.
Issue #217 - Handler class path wasn't updated as part of the changes in
issue #214.
Resolve #216 
Resolve #217
> Issue #216 and #217 - Fix default plugins and handler package

- doc/source/installation.rst
- doc/source/project_setup.rst
Added a note about Python 3.7 compatibility as note for 'Installation...' and 'Setting Up...' page.
Resolves #233
> Issue #233 - document Python 3.7 compatibility

- ait/core/__init__.py
- ait/core/api.py
- ait/core/bin/ait_cmd_send.py
- ait/core/bin/ait_seq_send.py
- ait/core/server/__init__.py
- ait/core/server/broker.py
- ait/core/server/client.py
- ait/core/server/server.py
- config/config.yaml
- doc/source/server_architecture.rst
- introduced concept of a command topic, which the server automatically create
- server will connect this topic to at most one outbound stream
- outbound stream config updated to include new field designating it
- if not outbound stream declares itself, then server will self-assign the first out stream
- updated server architecture docs to document the above
- CmdApi updated to send command+args to either ZMQ topic (default) or UDP.
- updated ait_cmd_send and ait_seq_send to include new options for specifying topic or udp.
Resolve #143
> Issue #143 - CmdApi utilizes newly added server command entry point

- ait/core/api.py
- ait/core/bin/ait_cmd_send.py
- ait/core/bin/ait_seq_send.py
Update CmdAPI's upd_dest argument to default to None. Instantiation of
CmdAPI without additional arguments will result in a connection to the
C&DH global 0MQ command port.
Update CmdAPI instantiations in ait-[cmd|seq]-send scripts to take the
keyword argument into consideration.
Resolve #281
> Issue #281 - Update CmdAPI with None udp_dest default

- setup.py
> Issue #297 - Pin greenlets to 0.4.16 for gevent 1.4 compatibility

- ait/core/cfg.py
- ait/core/test/test_cfg.py
Update the config directory expansion handling to support lists within
dictionary elements. This server rework added elements consisting of
lists of dictionaries, some of which contain elements that could require
path expansion. For example, the GUI plugin looks for static file
directory configuration which likely requires path expansion. These
changes fix the issue in parsing elements of this sort.
Resolve #306
> Issue #306 - Support lists in config directory expansion

- ait/core/db.py
- ait/core/dmc.py
- ait/core/test/test_db.py
This is a bit of a sweeping rework to parts of the database APIs to
provide a unification to result formatting. During testing a few issues
were run into specific to the SQLiteBackend implementation that resulted
in a complete rework to the data storage format. These changes are
related enough that I'm grouping them under a single pull request.
Related issues:
Issue #303 - Database API query and results abstraction
Issue #307 - SQLite Backend Simplification
Issue #310 - DB API Sqlite connection and creation handling fails
to properly cover cases
Add AITDBResult class to provide a minimal wrapper around all database
query results. Any API that executes a query and returns results now
returns an AITDBResult object. Users can access the queries execute, any
errors encountered, and the query …
> Database API Result Handling and SQLite bug fixes and improvements

- ait/core/__init__.py
- ait/core/api.py
- ait/core/server/server.py
- ait/core/server/test/test_server.py
- doc/source/api_intro.rst
- doc/source/index.rst
- doc/source/server_architecture.rst
Update API telemetry handling in the Instrument interface. Telemetry
monitoring now handles all valid packets in the telemetry dictionary.
Telemetry data is pulled from the C&DH server via the default telemetry
topic.
Server code has been updated to create a new input stream that takes
input from other valid telemetry streams and emits telemetry data under
the "default telemetry topic" so other code can listen for these data.
Input streams are either set via config or are defaulted, if possible, to
all input streams that emit data in the necessary format (PacketHandler
and CCSDSPacketHandler being the current ones).
Tests have been updated. Global AIT config has been updated so the
"default telemetry topic" can be pulled via ait.DEFAULT_TLM_TOPIC.
Resolve #313
> Issue #313 - Update API telemetry handling functionality

- ait/core/api.py
- ait/core/server/client.py
- ait/core/server/plugins/data_archive.py
- ait/core/server/utils.py
- doc/source/ait.core.server.rst
- doc/source/ait.core.server.utils.rst
Update server handling of data passing to use 0MQ's
`[send|recv]_multipart` calls instead of `[send|recv]_string`.
Utilities have been added under ait.core.server.utils for encoding /
decoding messages into the proper format to simplify code throughout.
Various hacks for handling the string-ified data have been removed.
Resolve #299
> Issue #299 - Update server 0MQ data passing

- ait/core/bin/ait_limits_find_dn.py
- doc/source/ait.core.bin.ait_limits_find_dn.rst
- doc/source/ait.core.bin.rst
- doc/source/command_line.rst
Add ait_limits_find_dn for extracting DN values for limit trip
thresholds specified in EU. Update command line documentation with new
script info.
Resolve #320
> Issue #320 - Add limits_find_dn utility

- ait/core/api.py
CmdAPI now properly references `serv_utils` instead of `server_utils`
TlmMonitor now properly grabs its sub socket via `self._sub` and decodes
received packet messages with an additional `pickle.loads`.
Resolve #325
> Issue #325 - Fix 0MQ data format update issues

- ait/core/bin/ait_seq_decode.py
- ait/core/bin/ait_seq_encode.py
- ait/core/bin/ait_seq_print.py
- ait/core/seq.py
Update seq.py to support extensions. Update all references to `seq.Seq`
to instead use the extension compatible `seq.createSeq`.
Note, for now all other internal seq classes are left along. This means
that extending an internal part of a sequence, such as SeqCmd, isn't
possible without some additional work on the user's part. I'm not sure
that this is a huge issue given the relative simplicity of the calls to
the other classes (so updating wouldn't be much of an issue) and the
perceived likelihood that most seq.py extensions will be to change
encoding / decoding.
Resovle #194
> Issue #194 - Add support for seq extensions

- ait/core/bin/ait_seq_decode.py
Update ait_seq_decode so the expected input file name format matches
that of ait_seq_encode.
Resolve #330
> Issue #330 - Fix seq encode / decode input format consistency

- ait/core/seq.py
Seq no longer tries to cast the sequence `id` argument on initialization so
creating a new Seq without an id is valid. This is useful when creating
a Seq from a binary encoded sequence file in which the sequence id is
encoded. By default, it will parse this out for you.
Resolve #335
> Issue #335 - Make Seq sequence id optional on initialization

- ait/core/bin/ait_seq_encode.py
Update all ait-seq-encode log messages to use f-strings. Fix a bug with
seqid not being saved after a cast to int and this causing an error when
formatting a log message during sequence write.
Resolve #337
> Issue #337 - Update ait-seq-encode log message formatting

- ait/core/db.py
- ait/core/dmc.py
- ait/core/server/plugins/openmct.py
- ait/core/test/test_db.py
- doc/source/plugin_openmct.rst
- openmct/ait_cfg_section.yaml
- openmct/ait_integration.js
The original version of the AIT OpenMct plugin supported realtime telemetry only.
This PR adds historial queries - which is supported by telemetry stored in a database.
The layer uses the newer AIT Database abstraction, and so should work with any supported Database implementation. 
Fixes #302
> Add historical query support to the OpenMCT plugin

- doc/source/telemetry_intro.rst
Add a note to the `type` attribute of the telemetry Field definition
documentation elaborating on the issues with 64-bit integers being
displayed by the frontend due to JavaScript's approach to number
representation.
Resolve #345
> Issue #345 - Document 64-bit integer limitation in GUI

- ait/core/bin/ait_table_decode.py
- ait/core/bin/ait_table_encode.py
- ait/core/data/table_schema.json
- ait/core/table.py
- ait/core/test/test_table.py
- config/table.yaml
- doc/source/c_and_dh_intro.rst
- doc/source/index.rst
Rework Core table support to provide users with more consistent and
understandable feature set. Table encoding / decoding functionality has
been (hopefully) simplified via simpler, more flexible APIs, extraction
of hardcoded functionality, and leveraging of other Core functionality
such as dtype.py where possible.
Table encoding and decoding APIs have been cleaned up and made more
flexible so users can pass inputs in expected formats. Some
functionality has been extracted out of table.py into the encode /
decode CLI scripts (where it arguably belonged to begin with) in an
effort to keep Core functionality and abstractions cleaner. For example,
writing a decoded table to a file is no longer a requirement as part of
table decoding.
Column field handling now uses date type information for …
> Issue #354 - Rework table support

- ait/core/table.py
- ait/core/test/test_table.py
- doc/source/c_and_dh_intro.rst
Update table encode / decode handling so fields using Time64/40/32 are
properly passed datetime objects and decode into a well formatted
datetime string. Passed time strings must be RFC3339 formatted and will
be returned as such when decoded. Tests have been updated with time
examples.
Documentation has been updated to indicate what data types we support
and also elaborate on when users may need to extend core classes if they
want to support other data types (e.g., CMD16 and EVR16).
Resolve #360
> Issue #360 - Fix time handling in table encode / decode

- ait/core/cmd.py
This is intended to help the end user diagnose typos in their command dictionaries.
The default error message is not descriptive enough for the user to quickly find their error.
Enables concise and useful failures logs for smoke testing dictionaries.
> Issue-395 Add try except when attempting to pack opcode into struct.

- ait/core/server/client.py
Fix to error:
builtins.OSError: [Errno 97] Address family not supported by protocol
when ipv6 disabled at kernel level
Fixes #399
> issue-#399 Fix error when IPV6 is disabled at kernel level

- ait/core/cfg.py
Add capability for ait-create-dirs to create the directories specified by the DSN blocks in config.yaml
Add DSN config.yaml path entries to AitConfig._datapaths
ait-create-dirs will now be able to create directories for the DSN block.
> Issue-394 Add DSN paths to ait-create-dirs

- ait/core/util.py
This change request is based on issue-371. Users were having problems with the serialization of their config files. It was found that the included config files were not being tested for creation date, so when an included config file was modified, the need to recreate the binary (.pkl file) was not being recognized by the software. This resulted in and out of date config file being loaded. This has now been fixed with the addition of a short method (check_yaml_timestamps()) and a change to the 'dirty' property, which, now calls check_yaml_timestamps() in the ObjectCache class in util.py.
Fixes #371
> testing nested includes during test for 'dirty' (pickle)

- ait/core/server/plugins/openmct.py
- doc/source/plugin_openmct.rst
- openmct/README
- openmct/ait_integration.js
- openmct/example-server/ait_integration.js
- openmct/example-server/index.html
- openmct/example-server/lib/http.js
- openmct/example-server/package.json
- openmct/example-server/server.js
Refactored the plugin to maintain a set of active-websockets to which realtime telemetry will be sent.
Server also maintains state of web-socket by handling messages: subscribe, unsubscribe, close
Each web-socket maintains a set of subscribed telemetry fields, so only those fields will be transmitted to the web-socket.
We also refactored how the AIT-OpenMct extensions are integrated with OpenMCT.  No longer do we download OpenMCT and modify its internal files.  Instead, we offer an example web-server that imports openmct as a dependency. This removes an earlier requirement of using an older version of OpenMCT (before they adopted Webpack).
Finally, updated documentation to capture the new approach for deployment.
Testing involved an AIT Config YAML with the following plugin info:
```
- …
```
> Issue 358: OpenMCT Plugin support for multiple clients and filtered telemetry

- ait/core/server/plugins/apid_routing.py
- doc/source/ait.core.server.plugins.apid_routing.rst
- doc/source/ait.core.server.plugins.rst
- tests/ait/core/server/test_apid_routing.py
Implements a plugin which routes CCSDS packets by APID based on a table described in a .yaml file.
Fixes #438
> Issue #438 - Add ability to route packets based on APID

- ait/core/server/plugins/apid_routing.py
- ait/core/util.py
Fixes #448. 
```
(ait_python37_venv) bseto@MT-304784 core % git push origin issue-448
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
Reorder python imports...............................(no files to check)Skipped
mypy.....................................................................Passed
black................................................(no files to check)Skipped
flake8...................................................................Passed
AIT TLM YAML check.......................................................P …
```
> Issue 448: Fix existing flake8 findings

- ait/core/table.py
- ait/core/util.py
- tests/ait/core/__init__.py
- tests/ait/core/server/test_apid_routing.py
- tests/ait/core/test_cfg.py
- tests/ait/core/test_pcap.py
- tests/ait/core/test_table.py
- tests/ait/core/test_tlm.py
In unit tests removed all code using _'tempfile'_ and replaced with code using the _TestFile_ class.
Moved _TestFile_ class from _tests/ait/core/__init__.py_ to _ait/core/util.py_.
Modified _TestFile_ class to include on _'options'_ argument for file creation options (e.g. "w+", "wb+",...)
Factored out redundante _TestFile_ class in _test/ait/core/server/test_apid_rounting.py_ and used the common class in _util.py_
Did some minor clean up of import orders, 1 change to a class name, and a couple of docstrings to more closely match PEP 8 style guide.
Verified no _'tempfile'_ imports exist in the _'tests'_ directory structure
Ran all the unittests
Updated the syntax for calling the Context Manager to match docstrings.
Fixes #370
> Issue #370: Use TempFile class throughout test suite

- doc/requirements.txt
- doc/source/api_intro.rst
- doc/source/conf.py
- doc/source/plugin_PacketAccumulator.rst
- doc/source/plugin_PacketPadder.rst
- readthedocs.yml
After a series of trial and error attempts, it seems we now should have AIT-Core readthedocs working.
It seems the main issues were:
1) We need to tell readthedocs to install Sphinx dependencies: sphinx-rtd-theme, sphinxcontrib-httpdomain
...via a requirements.txt.
We also had to update the ReadTheDocs admin settings to tell system about the requirements file.
https://readthedocs.org/dashboard/ait-core/advanced/
2) To resolve a recursion error when DMC loads the leapseconds file, we have to monkey-patch Sphinx, and this is done via adding that to the conf.py file
Also made some minor updates to a few RST files to get rid of some of the warnings.
Final proof of a successful docs build can be found here: https://readthedocs.org/projects/ait-core/builds/17445166/
Fixes #428
> Issue #428 - Fix readthedocs build

- ait/core/cmd.py
- ait/core/util.py
- ait/core/val.py
- tests/ait/core/test_cmd.py
- tests/ait/core/test_tlm.py
- tests/ait/core/test_val.py
Issue-201 Yaml file schema verification now works on included yaml files.
In the Validator class I renamed the validate() method validate_schema().  This is used in the unit test to validate evr.yaml, table.yaml and limits.yaml.  It is only  a  general schema check.
I removed the individual validate() methods from the CmdValidator(Validator) and TlmValidator(Validator) classes and moved a general validate() function to the Validator class.
Added get_included_files() to the Validator class to produce a list of yaml files that need to be validated.
Fixes #201
> Issue #201: Yaml file schema verification now works on included yaml files

- poetry.lock
- pyproject.toml
Make sure we only grab versions < 4.x now that tox 4 is out. Update
poetry.lock with updates.
Resolve #469
> Issue #469 - Update tox version pin to avoid 4.x releases

- README.rst
- ait/core/dtype.py
- doc/source/ait.core.bin.rst
- doc/source/ait.core.rst
- doc/source/ait.core.server.config.rst
- doc/source/ait.core.server.handlers.rst
- doc/source/ait.core.server.plugins.PacketAccumulator.rst
- doc/source/ait.core.server.plugins.PacketPadder.rst
- doc/source/ait.core.server.plugins.apid_routing.rst
- doc/source/ait.core.server.plugins.rst
- doc/source/ait.core.server.process.rst
- doc/source/ait.core.server.rst
- doc/source/ait.rst
- doc/source/command_intro.rst
- doc/source/data_types.rst
- doc/source/index.rst
- doc/source/telemetry_intro.rst
Update dtype.py to support user extensions via `dtype.CustomTypes`.
Calls to `dtype.get` now also check `CustomTypes.get` for class
instances. Users can extend `dtypeCustomTypes` via the normal
toolkit extensions interface.
Default `dtype.CustomTypes.get` always returns None so normal
behavior remains unchanged.
Add top-level Data Type documentation page. This page now explicitly
lists the built-in types that AIT supports. Additionally, information on
how to use the newly added extension support in dtypes is included as
well.
Update README's `sphinx-apidoc` call instructions to use
`--implicit-namespaces`. This is necessary to ensure that the `ait`
namespace is picked up and included in the API docs that are generated.
Without this files will be written starting with the `core` module. …
> Issue #376 - Add extension support to dtype.py

- .github/workflows/full_build.yaml
- tox.ini
Add a default build for any push to master or pull request that runs
the full `tox` build. This includes the test suite for all supported
python versions, the docs build, and the linting pipeline.
This is sufficient for a first pass but there are a couple of things we
might want to poke at. I could not get `actions/setup-python` caching of
poetry dependencies to work with `tox-gh-actions`. The lint run kept
failing because it couldn't find `pre-commit` even though it seemed to
have been installed properly. Should poke at this in a follow on ticket.
Would also be good to get a better build running to test package
deployment and the like. Bundling everything up and shipping it off to
test.pypi would be great. I'd also like to get a release build
integrated so we aren't manually doing that. …
> Issue #467 - Add baseline GH Actions build

- ait/core/log.py
Add minor type annotations in log.py to keep type checking happing in
AIT-GUI.
Resolve #491
> Issue #491 - Add logger type annotations for GUI mypy checks

- poetry.lock
- pyproject.toml
Temporarily pin pyyaml to 5.3.1 to avoid issues with Cython 3
Resolve #498
> Issue #498 - Temporarily pin pyyaml to 5.3.1

- ait/core/seq.py
There was a lingering reference to readBinary() and readText(). This updates two lines to use read_binary() and read_text() instead.
Resolves #504
> Update method calls to use read_binary() and read_text().
