NASA-AMMOS/AIT-Core

- bliss/core/dmc.py
> Issue #8 - Fix inconsistent default leap second file name

- README.md
Resolves #21
- Updates links with latest version on RTD
- Updates into paragraph
- Removes unneeded sections
> Issue #21 - Update README

- bliss/core/test/test_table.py
> Issue #47 - Add clean up for test table temp file

- README.md
> Issue #46 - Add docs build badge to README

- CHANGELOG.md
> Issue #55 - Fix missing CHANGELOG releases

- src/doc/dict/cmd/Makefile
- src/doc/dict/cmd/ait-cmddefs-tex
- src/doc/dict/tlm/Makefile
- src/doc/dict/tlm/ait-tlmdefs-tex
Last remaining BLISS updates in AIT Core.
> Issue #34: BLISS to AIT change for Latex dict software

- ait/core/dmc.py
- ait/core/test/test_dmc.py
> Issue #80 - Add default timestamp for get_GPS_offset_for_date

- doc/source/extensions.rst
- doc/source/index.rst
> Issue #92 - Add extensions documentation

- doc/source/index.rst
> Issue #94 - Fix typo in docs index

- ait/core/notify.py
> Issue #104: add unsecured SMTP server access

- .travis.yml
> Issue #109 - Add latest build release to travisci config

- doc/source/ait.core.bin.ait_tlm_simulate.rst
- doc/source/ait.core.bin.rst
- doc/source/api_intro.rst
- doc/source/bsc_intro.rst
- doc/source/command_line.rst
- doc/source/telemetry_intro.rst
Updates to telemetry documentation. Fixes for other doc build warnings.
Resolves #119
> Issue #119 - Update documentation on telemetry dictionary

- doc/source/telemetry_intro.rst
> Issue #121 - Expand telemetry when and dntoeu documentation

- ait/core/table.py
- ait/core/test/test_table.py
- Update relative path references
- Deleted outdated test
Resolves #115
> Issue #115 - Config file referenced with relative path

- ait/core/data/tlm_schema.json
- ait/core/test/test_tlm.py
- ait/core/tlm.py
- config/tlm.yaml
First stab at derived telemetry support. 
Resolves #7
> Issue #7 - Add support for derived telemetry values

- config/config.yaml
Adding notification options `threshold` and `frequency` with example values to config.
https://github.com/NASA-AMMOS/AIT-GUI/issues/92
> AIT-GUI Issue #92 - Update monitoring with notification throttling 

- ait/core/server/handler.py
Update PacketHandler.handle to return a pickled tuple.
Resolve #144
> Issue #144 - Serialize PacketHandler output

- doc/source/command_intro.rst
> Issue #99 - Add documentation about default command encoding format

- config/tlm.yaml
- doc/source/telemetry_intro.rst
> Issue #132 - Add derived telemetry documentation

- ait/core/server/handler.py
- ait/core/server/stream.py
> Issue #159 - Stream handles None return from handlers

- ait/core/server/plugin.py
> Issue #171 - Changed plugins to accept pickle.dumps as input

- ait/core/server/server.py
> Issue #169 - Changed pop to get in server plugin creation

- ait/core/server/handler.py
> Issue #162 - Added more robust handling of APID masking in CCSDSHandler

- config/tlm.yaml
- doc/source/telemetry_intro.rst
> Issue #184 - Changed Ethernet packet definition field name and updated docs

- ait/core/server/handler.py
Resolves #185 
Also removes extraneous byte array conversion in CCSDS packet handler.
> Issue #185 - Fixed CCSDS Packet Handler APID comparison

- ait/core/db.py
- ait/core/test/test_db.py
> Issue #178 - Added commit statement and quotation marks to SQLiteBackend

- config/config.yaml
- scripts/example_script.py
> Issue #190 - Add example script and update config script directory

- ait/core/db.py
- ait/core/test/test_db.py
> Issue #180 - Add timestamps to SQLite database tables

- config/config.yaml
- doc/source/command_intro.rst
- sequences/example_sequence.txt
> Issue #68 - Add sequence documentation and example

- doc/source/api_intro.rst
> Issue #67 - Correct packet names in API docs

- doc/source/index.rst
> Issue #211 - Fix typo in doc index page

- doc/source/installation.rst
Fixed project setup link in docs
> Issue #197 - Fixed project setup link in docs

- ait/core/server/plugins/openmct.py
Updated OpenMCT plugin to support configurable telemetry stream names
> Issue #215 - Update OpenMCT plugin to support configurable telemetry stream names

- config/config.yaml
Replaced dsn section to AIT-DSN dsn section
> Issue #224 - Merge config files between AIT-Core and AIT-DSN 

- doc/source/command_intro.rst
- doc/source/command_line.rst
> Issue #231 - Add SeqGen CLI script to sequence documentation

- ait/core/bin/ait_create_dirs.py
- ait/core/bin/ait_seq_encode.py
Fixed exception syntax errors due to py3 update
> Issue #228 - Fixed exception syntax errors

- readthedocs.yml
> Issue #251 - Specify Python version for RTD build

- ait/core/bin/ait_cmd_hist.py
- ait/core/bin/ait_pcap.py
- ait/core/bin/ait_table_decode.py
- ait/core/bin/ait_table_encode.py
- ait/core/dtype.py
- ait/core/table.py
- ait/core/test/test_dtype.py
Fixes #256, #257 , #258, #236, #241
> Python3 test updates for core and bin scripts, part 2

- ait/core/bin/ait_ccsds_send_example.py
> Issue #262 - Prevent auto execute on import for ait_ccsds_send_example

- doc/source/plugin_openmct.rst
> Issue #242 - Document dependency on OpenMCT v0.14.0

- ait/core/server/test/test_handler.py
Following tests were added:
* Check if packet length is at least 7 bytes
* Check if APID match between config and packet
*  Check packet length vs header reported length
*  Check if dumped uid match expected tlm dictionary uid
FYI, below is stdout of the unit tests:
```
(ait) LMC-062858:test kkallas$ nosetests test_handler.py
2020-04-17T07:04:16.405 | WARNING  | Config parameter dsn.cfdp.mib.path specifies nonexistent path /Users/kkallas/Documents/github/AIT/AIT-Core/config/mib
2020-04-17T07:04:16.407 | WARNING  | Config parameter dsn.cfdp.datasink.outgoing.path specifies nonexistent path /Users/kkallas/Documents/github/AIT/AIT-Core/ait/dsn/cfdp/datasink/outgoing
2020-04-17T07:04:16.409 | WARNING  | Config parameter dsn.cfdp.datasink.incoming.path specifies nonexistent path …
```
> Issue #239 - Add ccsds packet validation test

- ait/core/bin/ait_seq_decode.py
- ait/core/bin/ait_seq_encode.py
- ait/core/bin/ait_seq_print.py
Reverse indexing cleanup in ait_seq_print, ait_seq_decode, and ait-seq-encode.
> Issue #264 - Reverse indexing cleanup

- ait/core/db.py
> Issue #300 - Fix cfg import in db.py

- ait/core/server/server.py
> Issue #316 - Fix typo in server._load_streams_and_plugins

- ait/core/val.py
Remove sorting of validation error message to resolve TypeError. Note, we
could implementation our own exception here and address this issue but I
haven't noticed a problem with not sorting the messages.
Resolve #318
> Issue #318 - Fix validation error message sorting issue

- ait/core/seq.py
Update Seq so the magic number class attribute `Magic` and the hard
coded command size length are configurable on initialization of the
Seq class. Seq.Magic is now an instance attribute instead.
Resolve #329
> Issue #329 - Update Seq for configurable Magic number and command sizes

- doc/source/databases.rst
Add info on "time" field name constraint and add additional details on
relevant classes, server plugins, and config.
Resolve #341
> Issue #341 - Update database API docs page

- ait/core/bin/ait_tlm_csv.py
> Change CSV-generating fields file to open 'r' mode

- ait/core/bin/ait_tlm_csv.py
**Included in this PR**
**Ref**
* [Issue 351](https://github.com/NASA-AMMOS/AIT-Core/issues/351)
> Update ait-tlm-csv cmd packet option description

- ait/core/bin/ait_tlm_csv.py
- doc/source/command_line.rst
**Included in this PR**
**Ref**
* [Issue 352](https://github.com/NASA-AMMOS/AIT-Core/issues/352)
> Ait-tlm-csv fields argument fix

- ait/core/dtype.py
Minor fix to ArrayType. See [Issue 401](https://github.com/NASA-AMMOS/AIT-Core/issues/401) for details.
> Fix ArrayType encode bug

- ait/core/db.py
- tests/ait/core/test_db.py
Added more time handling in database layer insert method.
*Refs*
* In response to [issue 304](https://github.com/NASA-AMMOS/AIT-Core/issues/304)
> Improve time handling in database insert method

- ait/core/cmd.py
- ait/core/dtype.py
- config/cmd.yaml
- tests/ait/core/test_cmd.py
> Update getDefaultDict to return CmdDict extensions when applicable

- ait/core/server/plugins/PacketPadder.py
- doc/source/plugin_PacketPadder.rst
> Add Packet Padder Plugin

- ait/core/server/plugins/PacketAccumulator.py
- doc/source/plugin_PacketAccumulator.rst
> Add Packet Accumulator

- ait/core/util.py
> Issue 371: Fix calls to logger

- ait/core/cmd.py
- ait/core/db.py
- ait/core/util.py
> Minor fixes to issues found in master

- ait/core/server/client.py
+ Current publish implementation is too restrictive.
+ Plugins need capability to publish to arbitrary topic.
+ Required for DSN Issue https://github.com/NASA-AMMOS/AIT-DSN/issues/168
> Issue #168 Add ability for plugins to publish to arbitrary topic

- ait/core/cfg.py
- ait/core/cmd.py
- ait/core/server/plugins/openmct.py
- ait/core/util.py
> Issue 440: Fix existing Flake8 findings

- ait/core/db.py
> Issue #353: Update log error messages to use correct function names

- ait/core/pcap.py
pcap.py: Fixed `__str__()` (`PCapGlobalHeader` and `PCapPacketHeader`) to bring up to date with Python3.  They now return string values rather than byte arrays.
Fixes #374
> Issue #374: PCap headers' __str__() methods must return string

- ait/core/server/process.py
- poetry.lock
- pyproject.toml
Merge the new functionality to the multiprocess branch
> Set the plugin process title

- .github/workflows/full_build.yaml
> Issue #480 - Fix incorrect tox-gh-actions version install

- README.rst
> Issue #478 - Update README pyenv install instructions

- README.rst
Update README with RTD build status badge.
Resolve #483
> Issue #483- Add RTD build status badge to README

- README.rst
> Issue #485 - Add GH action build status badge to README

- README.rst
> Issue #487 - Drop old build status badges

- MANIFEST.in
> Issue #489 - Add PEP 561 compatibility changes
